/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.leafygreens.torterra

import kotlin.test.Test
import kotlin.test.assertTrue

class TorterraTest {
//    @Test fun testSomeLibraryMethod() {
//        val classUnderTest = Library()
//        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
//    }
}
