/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
  // Support convention plugins written in Kotlin. Convention plugins are
  // build scripts in 'src/main' that automatically become available as plugins in the main build.
  `kotlin-dsl`
}

repositories {
  // Use the plugin portal to apply community plugins in convention plugins.
  gradlePluginPortal()
}

dependencies {
  implementation("org.jetbrains.kotlin:kotlin-gradle-plugin")
  implementation("com.github.jengelman.gradle.plugins:shadow:6.1.0")
  implementation("io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.16.0-RC2")
}
